<?php $this->layout('shared::layout', ['title' => 'Page not found']) ?>

<?php $this->start('main') ?>
    <div class="row" style="margin-bottom: 60px;">
        <div class="col-md-6">
            <div>
                <h1 class="h2">Page not found</h1>
                <p class="lead">Sorry, it appears the page you are looking for does not exist on the server.</p>
        </div>
    </div>
<?php $this->stop(); ?>