<?php $this->layout('shared::layout', ['title' => 'Method not allowed']) ?>

<?php $this->start('main') ?>
    <div class="row" style="margin-bottom: 60px;">
        <div class="col-md-6 col-md-push-3">
            <div>
                <h1 class="h2">Method not allowed</h1>
                <p>Sorry, access via that method is disallowed.</p>
                <a href="/">Go back to the homepage</a>
        </div>
    </div>
<?php $this->stop(); ?>