<?php $this->layout('shared::layout', ['title' => $meta['title']]) ?>

<?php $this->start('main') ?>
    <div class="row" style="margin-bottom: 45px;">
        <div class="col-md-6 col-md-push-3">
            <div>
                <h1><?= $this->e($meta['title']) ?></h1>

                <p>An archive cataloguing my thoughts on software development.</p>

                <?php foreach ($this->find('log') as $log): ?>
                    <p>
                        <a href="/<?= $this->e($log->uri) ?>" title="<?= $this->e($log->meta['title']) ?>">
                            <?= $log->meta['title'] ?>
                        </a>
                    </p>
                <?php endforeach; ?>
            </div>
        </div>
    </div>
<?php $this->stop(); ?>