<?php $this->layout('shared::layout', ['title' => $meta['title']]) ?>

<?php $this->start('main') ?>
    <div class="row" style="margin-bottom: 45px;">
        <div class="col-md-6 col-md-push-3">
            <div>
                <p class="small text-center" style="margin-top: 15px;">
                    <?= $meta['date'] ?>
                </p>

                <h1><?= $this->e($meta['title']) ?></h1>

                <?= $content ?>
            </div>
        </div>
    </div>
    <hr>
    <div class="row">
        <?php foreach ($this->find('log')->whereNot('meta.title', $meta['title']) as $log): ?>
            <div class="col-md-3 col-md-push-3 text-left">
                <strong>
                    <a href="/<?= $this->e($log->uri) ?>" title="<?= $this->e($log->meta['title']) ?>">
                        <?= $log->meta['title'] ?>
                    </a>
                </strong>

                <p class="text-muted small"><?= $log->meta['date'] ?></p>
            </div>
        <?php endforeach; ?>
    </div>
<?php $this->stop(); ?>