<html>
<head>
    <title><?= $this->e($title) ?></title>
    <link href="//maxcdn.bootstrapcdn.com/bootswatch/3.3.5/paper/bootstrap.min.css" rel="stylesheet"/>
    <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css" rel="stylesheet"/>
    <link href="/css/prism.css" rel="stylesheet"/>
    <style>
        main {
            margin-top: 90px;
        }

        h1 {
            font-size: 40px;
        }

        h2 {
            font-size: 20px;
            margin-top: 30px;
        }

        blockquote {
            margin: 30px 0;
            width: 66.66%;
        }

        pre {
            margin: 30px 0;
        }

        code[class*="language-"], pre[class*="language-"] {
            background: #f9f9f9;
            border-radius: inherit;
            box-shadow: none;
            border: inherit;
            font-family: Menlo, Monaco, Consolas, 'Courier New', monospace;
            line-height: 1.85em;
            margin: 30px 0;
        }

        h1 + p,
        p.lead {
            border-bottom: 1px solid #eeeeee;
            padding-bottom: 23px;
            margin-bottom: 23px;
            font-size: 19.5px;
            font-weight: 300;
            line-height: 1.4;
        }

        date.date {
            display: block;
            font-size: 16px;
            font-weight: 300;
            line-height: 1.4;
        }
    </style>
</head>
<body>
<main class="container">
    <?= $this->section('main') ?>
    <div class="row">
        <div class="col-md-6 col-md-push-3">
            <p class="text-muted">
                <i class="fa fa-copyright"></i> <?= date('Y') ?> William Grant-Buckley
                &lt;<a href="mailto:hello@william.scot">hello@william.scot</a>&gt;
            </p>
        </div>
    </div>
</main>
<script src="//code.jquery.com/jquery-1.11.3.min.js"></script>
<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
<script src="/js/prism.js"></script>
<script>
    $(document).ready(function () {
        $('pre').addClass('language-php');
    });
</script>
</body>
</html>