<html>
<head>
    <title><?= $this->e($title) ?></title>
    <link href="//maxcdn.bootstrapcdn.com/bootswatch/3.3.5/paper/bootstrap.min.css" rel="stylesheet"/>
    <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css" rel="stylesheet"/>
    <link href="/css/prism.css" rel="stylesheet"/>
    <style>
        main {
            margin-top: 90px;
        }

        h1 {
            font-size: 40px;
        }

        h2 {
            font-size: 20px;
            margin-top: 30px;
        }

        blockquote {
            margin: 30px 0;
            width: 66.66%;
        }

        pre {
            margin: 30px 0;
        }

        code[class*="language-"], pre[class*="language-"] {
            background: #f9f9f9;
            border-radius: inherit;
            box-shadow: none;
            border: inherit;
            font-family: Menlo, Monaco, Consolas, 'Courier New', monospace;
            line-height: 1.85em;
            margin: 30px 0;
        }

        h1 + p {
            border-bottom: 1px solid #eeeeee;
            padding-bottom: 23px;
            margin-bottom: 23px;
            font-size: 19.5px;
            font-weight: 300;
            line-height: 1.4;
        }
    </style>
</head>
<body>
<div class="navbar navbar-default navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand">William.</a>
        </div>
        <div class="navbar-collapse collapse" id="navbar">
            <ul class="nav navbar-nav navbar-right">
                <li><a href="/log">Log</a></li>
                <li><a href="/contact">Contact</a></li>
            </ul>
        </div>
    </div>
</div>
<main class="container">
    <?= $this->section('main') ?>
</main>
<script src="//code.jquery.com/jquery-1.11.3.min.js"></script>
<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
<script src="/js/prism.js"></script>
<script>
    $(document).ready(function() {
        $('pre').addClass('language-php');
    });
</script>
</body>
</html>